import { expect, test } from "@playwright/test";

/**
 * This was generated by default by `npm init playwright@latest` and it demonstrates common test patterns.
 */
test.beforeEach(async ({ page }) => {
  await page.goto("http://localhost:8000/");
  await page.getByLabel("Command input").click();
});
test.afterEach(async ({ page }) => {
  await page.reload();
});

/**
 *  mode test
 */
test("type in mode command, expect to see display change", async ({ page }) => {
  await page.getByLabel("Command input").fill("mode");
  await page.getByLabel("Submit").click();
  await expect(page.getByText("Command: mode")).toBeVisible();
  await expect(
    page.getByText("Output: Switched to verbose mode")
  ).toBeVisible();
});

/**
 * mode after successful load -- verbose
 */
test("type in mode after successful load", async ({ page }) => {
  await page
    .getByPlaceholder("Enter command here!")
    .fill("load ./data/server-data/city-town-income.csv");
  await page.getByLabel("Submit").click();

  await page.getByLabel("Command input").fill("mode");
  await page.getByLabel("Submit").click();
  await expect(
    page.getByText("Command: load ./data/server-data/city-town-income.csv")
  ).toBeVisible();
  await expect(
    page.getByText(
      "Output: File ./data/server-data/city-town-income.csv loaded Successfully"
    )
  ).toBeVisible();
});

/**
 * successful load --> verbose mode --> brief mode
 */
test("toggling between modes", async ({ page }) => {
  await page
    .getByPlaceholder("Enter command here!")
    .fill("load ./data/server-data/city-town-income.csv");
  await page.getByLabel("Submit").click();

  await page.getByLabel("Command input").fill("mode");
  await page.getByLabel("Submit").click();
  await expect(
    page.getByText("Command: load ./data/server-data/city-town-income.csv")
  ).toBeVisible();
  await expect(
    page.getByText(
      "Output: File ./data/server-data/city-town-income.csv loaded Successfully"
    )
  ).toBeVisible();
  await page.getByLabel("Command input").fill("mode");
  await page.getByLabel("Submit").click();
  await expect(
    page.getByText("Command: load ./data/server-data/city-town-income.csv")
  ).not.toBeVisible();

  await expect(page.getByText("Output: Switched to brief mode")).toBeVisible();
});
